// The Global Trade System Protocol Buffer Definition

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.19.4
// source: pkg/gts/gts.proto

package gts

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Trade Request Messages
type TradeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RequestedPokemon string `protobuf:"bytes,1,opt,name=requested_pokemon,json=requestedPokemon,proto3" json:"requested_pokemon,omitempty"`
	OfferedPokemon   string `protobuf:"bytes,2,opt,name=offered_pokemon,json=offeredPokemon,proto3" json:"offered_pokemon,omitempty"`
	MinLvl           *int32 `protobuf:"varint,3,opt,name=min_lvl,json=minLvl,proto3,oneof" json:"min_lvl,omitempty"`
	MaxLvl           *int32 `protobuf:"varint,4,opt,name=max_lvl,json=maxLvl,proto3,oneof" json:"max_lvl,omitempty"`
}

func (x *TradeRequest) Reset() {
	*x = TradeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_gts_gts_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TradeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TradeRequest) ProtoMessage() {}

func (x *TradeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_gts_gts_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TradeRequest.ProtoReflect.Descriptor instead.
func (*TradeRequest) Descriptor() ([]byte, []int) {
	return file_pkg_gts_gts_proto_rawDescGZIP(), []int{0}
}

func (x *TradeRequest) GetRequestedPokemon() string {
	if x != nil {
		return x.RequestedPokemon
	}
	return ""
}

func (x *TradeRequest) GetOfferedPokemon() string {
	if x != nil {
		return x.OfferedPokemon
	}
	return ""
}

func (x *TradeRequest) GetMinLvl() int32 {
	if x != nil && x.MinLvl != nil {
		return *x.MinLvl
	}
	return 0
}

func (x *TradeRequest) GetMaxLvl() int32 {
	if x != nil && x.MaxLvl != nil {
		return *x.MaxLvl
	}
	return 0
}

// Trade Response Messages
type TradeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RequestedPokemon string `protobuf:"bytes,1,opt,name=requested_pokemon,json=requestedPokemon,proto3" json:"requested_pokemon,omitempty"`
	OfferedPokemon   string `protobuf:"bytes,2,opt,name=offered_pokemon,json=offeredPokemon,proto3" json:"offered_pokemon,omitempty"`
	Lvl              int32  `protobuf:"varint,3,opt,name=lvl,proto3" json:"lvl,omitempty"`
}

func (x *TradeResponse) Reset() {
	*x = TradeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_gts_gts_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TradeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TradeResponse) ProtoMessage() {}

func (x *TradeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_gts_gts_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TradeResponse.ProtoReflect.Descriptor instead.
func (*TradeResponse) Descriptor() ([]byte, []int) {
	return file_pkg_gts_gts_proto_rawDescGZIP(), []int{1}
}

func (x *TradeResponse) GetRequestedPokemon() string {
	if x != nil {
		return x.RequestedPokemon
	}
	return ""
}

func (x *TradeResponse) GetOfferedPokemon() string {
	if x != nil {
		return x.OfferedPokemon
	}
	return ""
}

func (x *TradeResponse) GetLvl() int32 {
	if x != nil {
		return x.Lvl
	}
	return 0
}

var File_pkg_gts_gts_proto protoreflect.FileDescriptor

var file_pkg_gts_gts_proto_rawDesc = []byte{
	0x0a, 0x11, 0x70, 0x6b, 0x67, 0x2f, 0x67, 0x74, 0x73, 0x2f, 0x67, 0x74, 0x73, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x11, 0x67, 0x6c, 0x6f, 0x62, 0x61, 0x6c, 0x54, 0x72, 0x61, 0x64, 0x65,
	0x53, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x22, 0xb8, 0x01, 0x0a, 0x0c, 0x54, 0x72, 0x61, 0x64, 0x65,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2b, 0x0a, 0x11, 0x72, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x65, 0x64, 0x5f, 0x70, 0x6f, 0x6b, 0x65, 0x6d, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x10, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x65, 0x64, 0x50, 0x6f, 0x6b,
	0x65, 0x6d, 0x6f, 0x6e, 0x12, 0x27, 0x0a, 0x0f, 0x6f, 0x66, 0x66, 0x65, 0x72, 0x65, 0x64, 0x5f,
	0x70, 0x6f, 0x6b, 0x65, 0x6d, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x6f,
	0x66, 0x66, 0x65, 0x72, 0x65, 0x64, 0x50, 0x6f, 0x6b, 0x65, 0x6d, 0x6f, 0x6e, 0x12, 0x1c, 0x0a,
	0x07, 0x6d, 0x69, 0x6e, 0x5f, 0x6c, 0x76, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x48, 0x00,
	0x52, 0x06, 0x6d, 0x69, 0x6e, 0x4c, 0x76, 0x6c, 0x88, 0x01, 0x01, 0x12, 0x1c, 0x0a, 0x07, 0x6d,
	0x61, 0x78, 0x5f, 0x6c, 0x76, 0x6c, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x48, 0x01, 0x52, 0x06,
	0x6d, 0x61, 0x78, 0x4c, 0x76, 0x6c, 0x88, 0x01, 0x01, 0x42, 0x0a, 0x0a, 0x08, 0x5f, 0x6d, 0x69,
	0x6e, 0x5f, 0x6c, 0x76, 0x6c, 0x42, 0x0a, 0x0a, 0x08, 0x5f, 0x6d, 0x61, 0x78, 0x5f, 0x6c, 0x76,
	0x6c, 0x22, 0x77, 0x0a, 0x0d, 0x54, 0x72, 0x61, 0x64, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x2b, 0x0a, 0x11, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x65, 0x64, 0x5f,
	0x70, 0x6f, 0x6b, 0x65, 0x6d, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x10, 0x72,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x65, 0x64, 0x50, 0x6f, 0x6b, 0x65, 0x6d, 0x6f, 0x6e, 0x12,
	0x27, 0x0a, 0x0f, 0x6f, 0x66, 0x66, 0x65, 0x72, 0x65, 0x64, 0x5f, 0x70, 0x6f, 0x6b, 0x65, 0x6d,
	0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x6f, 0x66, 0x66, 0x65, 0x72, 0x65,
	0x64, 0x50, 0x6f, 0x6b, 0x65, 0x6d, 0x6f, 0x6e, 0x12, 0x10, 0x0a, 0x03, 0x6c, 0x76, 0x6c, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x6c, 0x76, 0x6c, 0x32, 0x6c, 0x0a, 0x11, 0x47, 0x6c,
	0x6f, 0x62, 0x61, 0x6c, 0x54, 0x72, 0x61, 0x64, 0x65, 0x53, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x12,
	0x57, 0x0a, 0x0c, 0x47, 0x65, 0x74, 0x54, 0x72, 0x61, 0x64, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x12,
	0x1f, 0x2e, 0x67, 0x6c, 0x6f, 0x62, 0x61, 0x6c, 0x54, 0x72, 0x61, 0x64, 0x65, 0x53, 0x79, 0x73,
	0x74, 0x65, 0x6d, 0x2e, 0x54, 0x72, 0x61, 0x64, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x20, 0x2e, 0x67, 0x6c, 0x6f, 0x62, 0x61, 0x6c, 0x54, 0x72, 0x61, 0x64, 0x65, 0x53, 0x79,
	0x73, 0x74, 0x65, 0x6d, 0x2e, 0x54, 0x72, 0x61, 0x64, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x00, 0x28, 0x01, 0x30, 0x01, 0x42, 0x17, 0x5a, 0x15, 0x67, 0x69, 0x74, 0x68,
	0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x62, 0x63, 0x63, 0x6f, 0x72, 0x62, 0x2f, 0x67, 0x74,
	0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pkg_gts_gts_proto_rawDescOnce sync.Once
	file_pkg_gts_gts_proto_rawDescData = file_pkg_gts_gts_proto_rawDesc
)

func file_pkg_gts_gts_proto_rawDescGZIP() []byte {
	file_pkg_gts_gts_proto_rawDescOnce.Do(func() {
		file_pkg_gts_gts_proto_rawDescData = protoimpl.X.CompressGZIP(file_pkg_gts_gts_proto_rawDescData)
	})
	return file_pkg_gts_gts_proto_rawDescData
}

var file_pkg_gts_gts_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_pkg_gts_gts_proto_goTypes = []interface{}{
	(*TradeRequest)(nil),  // 0: globalTradeSystem.TradeRequest
	(*TradeResponse)(nil), // 1: globalTradeSystem.TradeResponse
}
var file_pkg_gts_gts_proto_depIdxs = []int32{
	0, // 0: globalTradeSystem.GlobalTradeSystem.GetTradeList:input_type -> globalTradeSystem.TradeRequest
	1, // 1: globalTradeSystem.GlobalTradeSystem.GetTradeList:output_type -> globalTradeSystem.TradeResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pkg_gts_gts_proto_init() }
func file_pkg_gts_gts_proto_init() {
	if File_pkg_gts_gts_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pkg_gts_gts_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TradeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_gts_gts_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TradeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_pkg_gts_gts_proto_msgTypes[0].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pkg_gts_gts_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_gts_gts_proto_goTypes,
		DependencyIndexes: file_pkg_gts_gts_proto_depIdxs,
		MessageInfos:      file_pkg_gts_gts_proto_msgTypes,
	}.Build()
	File_pkg_gts_gts_proto = out.File
	file_pkg_gts_gts_proto_rawDesc = nil
	file_pkg_gts_gts_proto_goTypes = nil
	file_pkg_gts_gts_proto_depIdxs = nil
}
